### PR TITLE
Fix #145 support synchronous response fns

### LINKED ISSUE #145: Confused about conditional mocking (doMockIf, doMockOnceIf)
I thought the need of mocking specific requests with specific responses and leave the other to the default behavior is a pretty common need and it was expressed by https://github.com/jefflau/jest-fetch-mock/issues/95 and I though it was solved by https://github.com/jefflau/jest-fetch-mock/pull/128 introducing `doMockIf` and `doMockOnceIf`.

I still fail to understand though how to properly mock 3 API calls *no matter the order* while leaving the other mocked by default.

- all the fetch calls mocked by default
- call to `/token` mocked with "randomtoken"
- call to `/info` mocked with some stub data
- call to `/islogged` mocked with `true`

I tried a chain like
```
fetch
   .doMockOnceIf(/islogged/, true)
   .doMockOnceIf(/token/, 'randomtoken')
   .doMockOnceIf(/info/, infoStub)
```
But that seems to mock properly only if the order of the calls is known and the calls are executed in sequence.

Am I missing something?

### PR DESCRIPTION
**Pull request by yinzara**

### CODE REVIEW

**Comment by yinzara** [comment]
We'll need to get #180 merged before the build is fixed.

File: tests/api.js [hunk 1]
```diff
@@ -2,21 +2,21 @@ require('cross-fetch/polyfill')
```
Comment (yinzara) [inline tests/api.js:2]: Forgot to reformat after prettier was implemented.

File: tests/node.test.js [hunk 2]
```diff
@@ -1,9 +1,9 @@
-/**
- * @jest-environment node
- */
-let DOMException = require('domexception')
-
-it('rejects with a dom exception', () => {
-  fetch.mockAbort()
-  expect(fetch('/')).rejects.toThrow(expect.any(DOMException))
-})
+/**
```
Comment (yinzara) [inline tests/node.test.js:1]: prettier reformat
